### PR TITLE
create category bug

### LINKED ISSUE #140: Fix Create Event bug with event not going to correct category
After creating an event, the new event shows up under "All Events" but doesn't get mapped to the correct category label when you view it in the Events Dashboard (aka `/events`).

We should investigate this because I have a feeling it affects volunteers not being able to see the events too. Some theories I have about the root cause are the backend event category enum not categorizing events properly or the frontend event dashboard not filtering them correctly when it fetches the events from the backend.

- Look into possible causes on frontend and/or backend and make the events properly map to the correct event type
- If you need to make a backend PR to fix stuff on the backend, just go ahead and make the PR and tag me and Claude to get it reviewed alongside this

### PR DESCRIPTION
**Pull request by ctc-devops**
After creating an event, the new event shows up under "All Events" but doesn't get mapped to the correct category label when you view it in the Events Dashboard (aka `/events`).

We should investigate this because I have a feeling it affects volunteers not being able to see the events too. Some theories I have about the root cause are the backend event category enum not categorizing events properly or the frontend event dashboard not filtering them correctly when it fetches the events from the backend.

- Look into possible causes on frontend and/or backend and make the events properly map to the correct event type
- If you need to make a backend PR to fix stuff on the backend, just go ahead and make the PR and tag me and Claude to get it reviewed alongside this
closes #140

### CODE REVIEW

**Comment by heyitsmichellelin** [comment]
### What changes are included in this PR?
Fixed remaining filter issues regarding the type of event (status already worked). Issue was related to case differences between compared values, the `type` parameter passed into the function that filters events was lowercase, but the event object attributes were uppercase and slightly different. Fix involved minor changes to compared values and using .toLowerCase on event object attributes.

We also verified that the Create Event functionality does work as intended. As long as address fields are entered correctly the event will be created. However, given some invalid inputs (such as zipcode), the event will not be created and will also give no feedback to the user.

### Instructions to test changes:
To test filter thoroughly, create a set of 6 events with each representing one of each type and status, and check all given filters. Ensure that all events tagged to a particular status are proper for their respective values.
`[Food Running | Upcoming] [Food Running | Past]`

`[Dist | Upcoming] [ Distribution | Past]`

`[Other | Upcoming] [Other | Past]`

### Images (if applicable)
Distribution Filter Image
dist
Food Running Filter Image
food running
Other Filter Image
other

(modified from [old PR](https://github.com/ctc-uci/abound-food-care-frontend/pull/145#issuecomment-1199974745))

File: src/components/events/AdminEvents/AdminEvents.jsx [hunk 1]
```diff
@@ -64,34 +64,66 @@ const AdminEvents = () => {
...
+  //   } else {
+  //     filteredEvents = filteredEvents.filter(
+  //       event =>
+  //         (event.eventType === type || event.eventType === 'null') &&
+  //         determineStatus(event.startDatetime) === status,
+  //     );
+  //   }
+  //   return filteredEvents;
+  // };
+
```
Comment (claudeisakeeb) [inline src/components/events/AdminEvents/AdminEvents.jsx]: remove comment

**Review by claudeisakeeb — CHANGES_REQUESTED** [review]
This is good, just 1 comment.

@alanchangxyz I think it's fine to just merge these changes in and then pagination can be a new PR. Thoughts?

File: src/components/events/AdminEvents/AdminEvents.jsx [hunk 2]
```diff
@@ -64,32 +64,39 @@ const AdminEvents = () => {
...
-        event =>
-          event.eventType === fieldToFilterBy ||
-          determineStatus(event.startDatetime) === fieldToFilterBy,
-      );
-    } else if (
-      (type === 'distribution' || type === 'food') &&
-      (status === 'upcoming' || status === 'past')
-    ) {
+    } else if (type === 'distribution') {
+      filteredEvents = filteredEvents.filter(event => event.eventType.toLowerCase() === type);
```
Comment (claudeisakeeb) [inline src/components/events/AdminEvents/AdminEvents.jsx]: Can we actually change this to be more consistent with the other comparisons? ie change type to distribution

**Review by claudeisakeeb — APPROVED** [review]
Looks good.

At this point I'm ok with not having an enum for these event types but let's see what alan has to say

File: src/components/events/AdminEvents/AdminEvents.jsx [hunk 3]
```diff
@@ -64,32 +64,41 @@ const AdminEvents = () => {
   const determineStatus = startDatetime =>
     new Date(startDatetime) > new Date() ? 'upcoming' : 'past';
 
+  const getEventsByStatus = (events, status) => {
+    let filteredEvents = events;
+    if (status === 'all') {
```
Comment (alanchangxyz) [inline src/components/events/AdminEvents/AdminEvents.jsx:69]: this is passable, but for future reference, a more concise way of doing this is:
```
const filteredEvents = {
"all": events,
"upcoming": events.filter(event => determineStatus(event.startDatetime) === 'upcoming',
"past": ...
};
return filteredEvents[status];
```

**Comment by alanchangxyz** [comment]
> Looks good.
> 
> At this point I'm ok with not having an enum for these event types but let's see what alan has to say

Yeah enum would be nice but at this point functional is functional. We don't need to worry about it for now

**Comment by alanchangxyz** [comment]
> This is good, just 1 comment.
> 
> @alanchangxyz I think it's fine to just merge these changes in and then pagination can be a new PR. Thoughts?

Separating it to new PR

**Comment by alanchangxyz** [comment]
Ok this is officially LGTM. Merging
