### PR TITLE
ModuleCSS + Global styles/fonts + Fix File Hierarchy + Navbar refactor

### LINKED ISSUE #138: Change css to module.css & add AFC fonts as globals
## What changes are included in this PR?
- Change .css files to .module.css to prevent overriding styles across components and pages
- Add AFC fonts used in figma for easier access and usage
- **NEW: Navbar now refactored to separate admin/volunteer tabs more easily**

## Instructions to test changes:
- .css files converted to module.css
- AFC fonts properly applying globally

### PR DESCRIPTION
**Pull request by alanchangxyz**

### CODE REVIEW

File: src/components/NavMenu/NavMenu.jsx [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+import styles from './NavMenu.module.css';
+import './NavAnt.css';
+
+const { Sider } = Layout;
+
+const NavMenu = ({ isAdmin }) => {
+  const [collapsed, setCollapsed] = useState(false);
+  const [menuTitle, setMenuTitle] = useState('Abound Food Care');
+  const location = useLocation();
+  console.log(location.pathname);
```
Comment (ctc-devops) [inline src/components/NavMenu/NavMenu.jsx]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: src/components/events/createEvent/EventsAdditionalInfo.jsx [hunk 2]
```diff
@@ -5,7 +5,7 @@ import { RightOutlined } from '@ant-design/icons';
 import PropTypes from 'prop-types';
 import WaiversGrid from '../../waivers/WaiversGrid';
 import useViewPort from '../../../common/useViewPort';
-import './createEvent.css';
+import styles from './CreateEvent.module.css';
```
Comment (ctc-devops) [inline src/components/events/createEvent/EventsAdditionalInfo.jsx:8]: 🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module './CreateEvent.module.css'.

File: src/components/events/createEvent/EventsGeneralInfo.jsx [hunk 3]
```diff
@@ -16,7 +16,7 @@ import {
 } from 'antd';
 import useViewPort from '../../../common/useViewPort';
 import EventTypeModal from './EventTypeModal';
-import './createEvent.css';
+import styles from './CreateEvent.module.css';
```
Comment (ctc-devops) [inline src/components/events/createEvent/EventsGeneralInfo.jsx:19]: 🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module './CreateEvent.module.css'.

File: src/components/events/event/EventPage/EventPage.jsx [hunk 4]
```diff
@@ -6,13 +6,13 @@ import {
...
-import { Button, Divider, Tag, Space, ConfigProvider } from 'antd';
+import { Button, Divider, Tag, Space } from 'antd';
 import moment from 'moment';
-import { AFCBackend } from '../../../util/utils';
-import PostEvent from './postevent/PostEvent';
-import EventVolunteerList from './volunteer-list/EventVolunteerList';
-import EventPageImage from '../../../assets/img/event-page-banner.png';
-import './eventPage.css';
+import { AFCBackend } from '../../../../util/utils';
+import PostEvent from '../PostEvent/PostEvent';
```
Comment (ctc-devops) [inline src/components/events/event/EventPage/EventPage.jsx:12]: 🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module '../PostEvent/PostEvent'.

Comment (ctc-devops) [inline src/components/events/event/EventPage/EventPage.jsx:12]: 🚫 **[eslint]** <[import/extensions](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/extensions.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing file extension for "../PostEvent/PostEvent"

File: src/pages/CreateEvent.jsx [hunk 5]
```diff
@@ -6,8 +6,8 @@ import { yupResolver } from '@hookform/resolvers/yup';
 import { Form, Button } from 'antd';
 import moment from 'moment';
 import uploadWaiver from '../components/events/utils';
-import EventsGeneralInfo from '../components/events/createEvent/EventsGeneralInfo';
-import EventsAdditionalInfo from '../components/events/createEvent/EventsAdditionalInfo';
+import EventsGeneralInfo from '../components/events/CreateEvent/EventsGeneralInfo';
```
Comment (ctc-devops) [inline src/pages/CreateEvent.jsx:9]: 🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module '../components/events/CreateEvent/EventsGeneralInfo'.

Comment (ctc-devops) [inline src/pages/CreateEvent.jsx:9]: 🚫 **[eslint]** <[import/extensions](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/extensions.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing file extension for "../components/events/CreateEvent/EventsGeneralInfo"

File: src/pages/CreateEvent.jsx [hunk 6]
```diff
@@ -6,8 +6,8 @@ import { yupResolver } from '@hookform/resolvers/yup';
...
+import EventsAdditionalInfo from '../components/events/CreateEvent/EventsAdditionalInfo';
```
Comment (ctc-devops) [inline src/pages/CreateEvent.jsx:10]: 🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module '../components/events/CreateEvent/EventsAdditionalInfo'.

Comment (ctc-devops) [inline src/pages/CreateEvent.jsx:10]: 🚫 **[eslint]** <[import/extensions](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/extensions.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing file extension for "../components/events/CreateEvent/EventsAdditionalInfo"
